### ISSUE TITLE
Shard Quantlib.Time into it's own package?

### ISSUE THREAD

**Issue by o1lo01ol1o** [paulrzcz/hquantlib#26]
Hi,
  We frequently run into a need to compute business days with respect to various calendars.  The  Quantlib.Time looks great for this task but the `hmatrix` dependency is prohibitive for compiling to GHCJS / ARM / iOS.  

Any chance you'd consider making it a separate package?

**Comment by paulrzcz** [comment]
Hi,
Yeah, I agree that Quantlib.Time should be a separate package. I was wondering why it is in C++ version of Quantlib.

I will start on it. It should not take much time to do.

**Comment by paulrzcz** [comment]
It is there: http://hackage.haskell.org/package/hquantlib-time
And repo is: https://github.com/paulrzcz/hquantlib-time

Feel free to contribute! Thanks for the idea!
